-- MySQL Script generated by MySQL Workbench
-- Wed Jun 22 08:40:31 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema parquindb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema parquindb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `parquindb` DEFAULT CHARACTER SET utf8 ;
USE `parquindb` ;

-- -----------------------------------------------------
-- Table `parquindb`.`PROFILES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parquindb`.`PROFILES` (
  `profile` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`profile`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parquindb`.`USERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parquindb`.`USERS` (
  `uid` VARCHAR(25) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `lastName` VARCHAR(50) NOT NULL,
  `profile` VARCHAR(10) NOT NULL,
  `recordDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastUpdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`uid`),
  INDEX `fk_USERS_PROFILES_idx` (`profile` ASC),
  CONSTRAINT `fk_USERS_PROFILES`
    FOREIGN KEY (`profile`)
    REFERENCES `parquindb`.`PROFILES` (`profile`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parquindb`.`STATUS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parquindb`.`STATUS` (
  `status` VARCHAR(4) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parquindb`.`TYPE_OF_PARKINGS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parquindb`.`TYPE_OF_PARKINGS` (
  `typeOfParking` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`typeOfParking`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parquindb`.`PARKINGS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parquindb`.`PARKINGS` (
  `idParking` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `status` VARCHAR(4) NOT NULL,
  `dueDate` TIMESTAMP NOT NULL,
  `owner` VARCHAR(25) NOT NULL,
  `typeOfParking` VARCHAR(20) NOT NULL,
  `moreDetails` TINYINT(1) NOT NULL DEFAULT 0,
  `timeZone` INT NOT NULL DEFAULT -5,
  `recordDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastUpdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idParking`),
  INDEX `fk_PARKINGS_STATUS1_idx` (`status` ASC),
  INDEX `fk_PARKINGS_USERS1_idx` (`owner` ASC),
  INDEX `fk_PARKINGS_TYPE_OF_PARKINGS1_idx` (`typeOfParking` ASC),
  CONSTRAINT `fk_PARKINGS_STATUS1`
    FOREIGN KEY (`status`)
    REFERENCES `parquindb`.`STATUS` (`status`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_PARKINGS_USERS1`
    FOREIGN KEY (`owner`)
    REFERENCES `parquindb`.`USERS` (`uid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_PARKINGS_TYPE_OF_PARKINGS1`
    FOREIGN KEY (`typeOfParking`)
    REFERENCES `parquindb`.`TYPE_OF_PARKINGS` (`typeOfParking`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parquindb`.`IMAGES`
-- -----------------------------------------------------
-- CREATE TABLE IF NOT EXISTS `parquindb`.`IMAGES` (
-- )
-- ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parquindb`.`COORDINATES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parquindb`.`COORDINATES` (
  `idCoordinate` INT NOT NULL,
  `latitude` DECIMAL(18,15) NOT NULL,
  `longitude` DECIMAL(18,15) NOT NULL,
  `lastUpdate` TIMESTAMP NOT NULL,
  PRIMARY KEY (`idCoordinate`),
  CONSTRAINT `fk_COORDINATES_PARKINGS1`
    FOREIGN KEY (`idCoordinate`)
    REFERENCES `parquindb`.`PARKINGS` (`idParking`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parquindb`.`ADDRESSES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parquindb`.`ADDRESSES` (
  `idAddress` INT NOT NULL,
  `line1` VARCHAR(45) NOT NULL,
  `line2` VARCHAR(45) NULL,
  `neighborhood` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `zip` VARCHAR(6) NOT NULL,
  `lastUpdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idAddress`),
  CONSTRAINT `fk_ADDRESSES_PARKINGS1`
    FOREIGN KEY (`idAddress`)
    REFERENCES `parquindb`.`PARKINGS` (`idParking`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parquindb`.`PRICES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parquindb`.`PRICES` (
  `idPrice` INT NOT NULL,
  `isFixed` TINYINT(1) NOT NULL DEFAULT 0,
  `hasDifferentFees` TINYINT(1) NOT NULL DEFAULT 0,
  `price` DECIMAL NOT NULL DEFAULT 0,
  `periodDuration` INT NOT NULL DEFAULT 0,
  `minutesTolerance` INT NOT NULL DEFAULT 0,
  `minutesToleranceAfterPay` INT NOT NULL DEFAULT 0,
  `recordDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastUpdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idPrice`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parquindb`.`TICKETS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parquindb`.`TICKETS` (
  `idTicket` INT NOT NULL,
  `idParking` INT NOT NULL,
  `arrivalDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `departureDate` TIMESTAMP NULL,
  `plate` VARCHAR(10) NOT NULL,
  `color` VARCHAR(15) NULL,
  `brand` VARCHAR(15) NULL,
  `model` VARCHAR(20) NULL,
  `idPrice` INT NOT NULL,
  `total` DECIMAL NOT NULL DEFAULT 0,
  PRIMARY KEY (`idTicket`),
  INDEX `fk_TICKETS_PRICES1_idx` (`idPrice` ASC),
  INDEX `fk_TICKETS_PARKINGS1_idx` (`idParking` ASC),
  CONSTRAINT `fk_TICKETS_PRICES1`
    FOREIGN KEY (`idPrice`)
    REFERENCES `parquindb`.`PRICES` (`idPrice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TICKETS_PARKINGS1`
    FOREIGN KEY (`idParking`)
    REFERENCES `parquindb`.`PARKINGS` (`idParking`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parquindb`.`DAYS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parquindb`.`DAYS` (
  `idDay` INT NOT NULL,
  `shorDay` VARCHAR(3) NOT NULL,
  `day` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idDay`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parquindb`.`SCHEDULES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parquindb`.`SCHEDULES` (
  `idSchedule` INT NOT NULL,
  `openingTime` TIME NOT NULL,
  `closingTime` TIME NOT NULL,
  `idDay` INT NOT NULL,
  `lastUpdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idSchedule`),
  INDEX `fk_SCHEDULES_DAYS1_idx` (`idDay` ASC),
  CONSTRAINT `fk_SCHEDULES_DAYS1`
    FOREIGN KEY (`idDay`)
    REFERENCES `parquindb`.`DAYS` (`idDay`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parquindb`.`PARKINGS_has_PRICES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parquindb`.`PARKINGS_has_PRICES` (
  `idParking` INT NOT NULL,
  `idPrice` INT NOT NULL,
  PRIMARY KEY (`idParking`, `idPrice`),
  INDEX `fk_PARKINGS_has_PRICES_PRICES1_idx` (`idPrice` ASC),
  INDEX `fk_PARKINGS_has_PRICES_PARKINGS1_idx` (`idParking` ASC),
  CONSTRAINT `fk_PARKINGS_has_PRICES_PARKINGS1`
    FOREIGN KEY (`idParking`)
    REFERENCES `parquindb`.`PARKINGS` (`idParking`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_PARKINGS_has_PRICES_PRICES1`
    FOREIGN KEY (`idPrice`)
    REFERENCES `parquindb`.`PRICES` (`idPrice`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parquindb`.`PARKINGS_has_SCHEDULES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parquindb`.`PARKINGS_has_SCHEDULES` (
  `idParking` INT NOT NULL,
  `idSchedule` INT NOT NULL,
  PRIMARY KEY (`idParking`, `idSchedule`),
  INDEX `fk_PARKINGS_has_SCHEDULES_SCHEDULES1_idx` (`idSchedule` ASC),
  INDEX `fk_PARKINGS_has_SCHEDULES_PARKINGS1_idx` (`idParking` ASC),
  CONSTRAINT `fk_PARKINGS_has_SCHEDULES_PARKINGS1`
    FOREIGN KEY (`idParking`)
    REFERENCES `parquindb`.`PARKINGS` (`idParking`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_PARKINGS_has_SCHEDULES_SCHEDULES1`
    FOREIGN KEY (`idSchedule`)
    REFERENCES `parquindb`.`SCHEDULES` (`idSchedule`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parquindb`.`STAFF`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parquindb`.`STAFF` (
  `idParking` INT NOT NULL,
  `uid` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idParking`, `uid`),
  INDEX `fk_PARKINGS_has_USERS_USERS1_idx` (`uid` ASC),
  INDEX `fk_PARKINGS_has_USERS_PARKINGS1_idx` (`idParking` ASC),
  CONSTRAINT `fk_PARKINGS_has_USERS_PARKINGS1`
    FOREIGN KEY (`idParking`)
    REFERENCES `parquindb`.`PARKINGS` (`idParking`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_PARKINGS_has_USERS_USERS1`
    FOREIGN KEY (`uid`)
    REFERENCES `parquindb`.`USERS` (`uid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parquindb`.`PROVIDERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parquindb`.`PROVIDERS` (
  `idProvider` INT NOT NULL AUTO_INCREMENT,
  `provider` VARCHAR(15) NULL,
  PRIMARY KEY (`idProvider`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parquindb`.`USERS_has_PROVIDERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parquindb`.`USERS_has_PROVIDERS` (
  `uid` VARCHAR(25) NOT NULL,
  `idProvider` INT NOT NULL,
  PRIMARY KEY (`uid`, `idProvider`),
  INDEX `fk_USERS_has_PROVIDERS_PROVIDERS1_idx` (`idProvider` ASC),
  INDEX `fk_USERS_has_PROVIDERS_USERS1_idx` (`uid` ASC),
  CONSTRAINT `fk_USERS_has_PROVIDERS_USERS1`
    FOREIGN KEY (`uid`)
    REFERENCES `parquindb`.`USERS` (`uid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_USERS_has_PROVIDERS_PROVIDERS1`
    FOREIGN KEY (`idProvider`)
    REFERENCES `parquindb`.`PROVIDERS` (`idProvider`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parquindb`.`FEES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parquindb`.`FEES` (
  `idFee` INT NOT NULL AUTO_INCREMENT,
  `order` INT NOT NULL,
  `periodDuration` INT NOT NULL DEFAULT 0,
  `price` DECIMAL NOT NULL DEFAULT 0,
  PRIMARY KEY (`idFee`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parquindb`.`PRICES_has_FEES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parquindb`.`PRICES_has_FEES` (
  `idPrice` INT NOT NULL,
  `idFee` INT NOT NULL,
  PRIMARY KEY (`idPrice`, `idFee`),
  INDEX `fk_PRICES_has_FEES_FEES1_idx` (`idFee` ASC),
  INDEX `fk_PRICES_has_FEES_PRICES1_idx` (`idPrice` ASC),
  CONSTRAINT `fk_PRICES_has_FEES_PRICES1`
    FOREIGN KEY (`idPrice`)
    REFERENCES `parquindb`.`PRICES` (`idPrice`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_PRICES_has_FEES_FEES1`
    FOREIGN KEY (`idFee`)
    REFERENCES `parquindb`.`FEES` (`idFee`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
